name: Build Project

on:
  workflow_dispatch: # Позволяет запускать действие вручную

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Configure vcpkg
      run: |
        echo {
          "default-registry": {
            "kind": "git",
            "repository": "https://github.com/microsoft/vcpkg",
            "baseline": "commit_hash_here"
          },
          "registries": [
            {
              "kind": "git",
              "repository": "https://gitlab.com/colorglass/vcpkg-colorglass",
              "baseline": "eb2f2bd143b8f7c52b57ef5a822163b56f7be7d6",
              "packages": [
                "commonlibsse-ng",
                "commonlibsse-ng-ae",
                "commonlibsse-ng-se",
                "commonlibsse-ng-vr",
                "commonlibsse-ng-flatrim"
              ]
            }
          ]
        } > vcpkg-configuration.json

    - name: Install dependencies
      run: .\vcpkg\vcpkg.exe install commonlibsse-ng simpleini magic-enum rapidjson

    - name: Configure CMake
      run: cmake -S . -B build --preset=FLATRIM

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Copy DLLs
      run: |
        mkdir dist\SKSE\Plugins
        xcopy "build\release\*.dll" "dist\SKSE\Plugins\" /I /Y
        xcopy "build\release\*.pdb" "dist\SKSE\Plugins\" /I /Y

    - name: Copy package
      run: xcopy "package" "dist" /I /Y /E